### ISSUE TITLE
KanBanNiang resources download failed. Reason: java.net.UnknownHostException: ftp.stackoverflow.wiki

### ISSUE THREAD

**Issue by Banqc0621** [adlered/bolo-solo#259]
为了方便自己修改程序后，直接打成war包替换，服务器使用war包进行docker-compose自定义部署，编写的docker-compose.yml内容：

```
version: '3'

services:
  # Web应用容器
  web:
    image: tomcat:9.0.56-jdk8-temurin-focal
    container_name: blog-web
    ports:
      - "8080:8080"  # 暴露应用的端口
    volumes:
      - ./bolo.war:/usr/local/tomcat/webapps/ROOT.war  # 将WAR文件挂载到Tomcat
    depends_on:
      - db  # 确保数据库在 Web 容器之前启动
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://blog-db:3306/blog_db  # MySQL 地址
      - SPRING_DATASOURCE_USERNAME=root  # 用户名
      - SPRING_DATASOURCE_PASSWORD=xxx  # 密码
    dns: 8.8.8.8
    networks:
      - app-network

  # MySQL容器
  db:
    image: mysql:5.7
    container_name: blog-db
    ports:
      - "3306:3306"  # 暴露数据库端口
    restart: always # 容器随docker启动自启
    volumes:
      - ./blog-db/conf.d:/etc/mysql/conf.d # 映射配置目录，宿主机:容器
      - ./blog-db/logs:/var/log/mysql # 映射日志目录，宿主机:容器
      - ./blog-db/data:/var/lib/mysql # 映射数据目录，宿主机:容器
      - /etc/localtime:/etc/localtime:ro # 让容器的时钟与宿主机时钟同步，避免时间的问题，ro是read only的意思，就是只读。
    environment:
      - MYSQL_ROOT_PASSWORD=xxx # MySQL的root密码
    networks:
      - app-network

  # Nginx反向代理容器，使用SSL证书
  nginx:
    image: nginx:latest
    container_name: blog-nginx
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf # 映射 Nginx 配置文件到容器内部
      - ./nginx/logs:/etc/nginx/logs # 映射 Nginx 日志文件到容器内部
      - ./nginx/cert:/etc/nginx/cert # 映射 Nginx cert，ssl证书文件到容器内部
    ports:
      - "80:80"    # HTTP
      - "443:443"  # HTTPS
    depends_on:
      - web  # 确保Web服务在Nginx之前启动
    networks:
      - app-network

# 自定义网络
networks:
  app-network:

```

想请教下，我本地部署没问题，部署到服务器报这个错误，自己写的docker-compose.yml，加了**dns： 8.8.8.8**还是报这个：**KanBanNiang resources download failed.**程序启动成功，也能登录页面，服务器上是这样的：

![Image](https://github.com/user-attachments/assets/ee52d612-6385-4686-9165-9c276c818278)

![Image](https://github.com/user-attachments/assets/2a2ae8d7-2776-4323-aff5-5c07148140d3)

问题：本地运行就能下载，这个KanBanNiang是什么呢？对项目有影响吗？如何解决呢
![Image](https://github.com/user-attachments/assets/321178de-33f4-4d12-b44b-96c845ac5d8a)
